default:
  model_dir: "modifiedDM_betaSurvival_dataJoint"
  start_density: 0.3
  phi_mu: 0.78
  psi_phi: 5
  max_counties: 15
  n_chains: 3

dev:
  top_dir: "~/../Desktop/fosteR"
  data_dir: "pigs-statistical/data"
  project_dir: "pigs-simulation"
  out_dir: "out"
  dev_dir: "dev"
  analysis_dir: "analysis"
  n_pp: 30
  n_mcmc: 500
  n_iter: 1000

hpc_test:
  top_dir: "/lustrefs/ceah/feral-swine"
  project_dir: "simulation"
  out_dir: "output"
  dev_dir: "test"
  analysis_dir: "analysis"
  data_dir: "data"
  n_pp: 30
  n_mcmc: 500
  n_iter: 5000

hpc_production:
  inherits: hpc_test
  dev_dir: "production"
  n_pp: 75
  n_mcmc: 1000
  n_iter: 100000
