default:
  n_pp: 30
  start_density: 5
  data_dir: "C://Users/John.Foster/OneDrive - USDA/Desktop/fosteR/pigs-statistical/data"
  out_dir: "out"
  analysis_dir: "analysis"
  model_dir: "modifiedDM_betaSurvival_dataJoint"
  phi_mu: 0.78
  psi_phi: 5
  n_mcmc: 500
  n_iter: 5000
  n_chains: 3

hpc_test:
  top_dir: "/lustrefs/ceah/feral-swine"
  project_dir: "simulation"
  out_dir: "output"
  analysis_dir: "analysis"
  data_dir: "data"

hpc_production:
  inherits: hpc_test
  n_pp: 75
  n_mcmc: 1000
  n_iter: 100000
